/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import AdministrarTablero.ActividadeDetalle;
import AdministrarTablero.ActividadesLista;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static metodos.ActividadMetodo.DevolverActividadDetalleArray;
import static metodos.ActividadMetodo.ModificarArchivoTxtActividadDetalle;
import metodos.ListaActividadesMetodo;
import static metodos.Metodos.DevolverTablaArreglo;
import static metodos.Metodos.ModificarArchivoTxt;

/**
 *
 * @author Eleazar
 */
public class ActividadesDetalle extends javax.swing.JFrame {

    DefaultTableModel mdlTable;
    ActividadesLista actividadesL = new ActividadesLista();

    ListaActividadesMetodo metodoActividades = new ListaActividadesMetodo();
    String CodigoTareaDetalle;
    Vector vCabeceras = new Vector();
    String CodigoListaTarea;
    String NombreTarea;
    String DescTarea;
    String FechaI;
    String FechaF;
    String CodigoTablero;
    String NombreTablero;
    String NombreListadoTarea;
    String CodigoActividad;
    String CodigoListaDetalle;

    /**
     * Creates new form ListaComentarios
     */
    public ActividadesDetalle(String CodigoListaTarea, String CodigoTareaDetalle, String NombreTarea, String DescTarea, String FechaI, String FechaF, String CodigoTablero, String NombreTablero, String NombreListaTarea, String CodgioActividad, String NombreActividad, String Estado, String CodigoACtividadDetalle) {
        initComponents();
        if (!"".equals(CodigoTareaDetalle)) {
            this.CodigoListaTarea = CodigoListaTarea;
            this.CodigoTareaDetalle = CodigoTareaDetalle;
            this.NombreTarea = NombreTarea;
            this.DescTarea = DescTarea;
            this.FechaI = FechaI;
            this.FechaF = FechaF;
            this.CodigoTablero = CodigoTablero;
            this.NombreTablero = NombreTablero;
            this.NombreListadoTarea = NombreListaTarea;
            this.CodigoTareaDetalle = CodigoTareaDetalle;
            this.CodigoListaDetalle = CodgioActividad;
            this.CodigoActividad = CodigoACtividadDetalle;

            ddlEstado.addItem("Sin completar");
            ddlEstado.addItem("Completado");
            txtnombreActividad.setText(NombreActividad);

            this.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
            this.setResizable(false); //Que no se pueda cambiar el tamaño

        } else {
            Inicio inicio = new Inicio();
            inicio.setVisible(true);
            this.setVisible(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnombreActividad = new javax.swing.JTextField();
        btnModificarActividad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btbRegresar = new javax.swing.JButton();
        ddlEstado = new java.awt.Choice();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Listado de Actividades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtnombreActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        btnModificarActividad.setText("Modificar Actividad");
        btnModificarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActividadActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel1.setText("Nombre de Actividad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btbRegresar.setText("Regresar");
        btbRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btbRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        ddlEstado.setBackground(new java.awt.Color(153, 153, 153));
        ddlEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(ddlEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        lblMensaje.setForeground(new java.awt.Color(51, 153, 0));
        lblMensaje.setText("mensaje");
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActividadActionPerformed
        if (!"".equals(txtnombreActividad.getText().trim())) {
            String NombreActividad = txtnombreActividad.getText();
            String Estado = ddlEstado.getSelectedItem();
            if (!"".equals(NombreTablero)) {
                ArrayList<ActividadeDetalle> ListaTA = DevolverActividadDetalleArray("Actividades\\" + this.CodigoListaDetalle + ".txt");
                ActividadeDetalle ModficarActividad = ListaTA.stream().filter(t -> t.getCodigoActividad().equals(this.CodigoActividad)).findFirst().get();
                ModficarActividad.setCodigoListaActividad(this.CodigoListaDetalle.trim());
                ModficarActividad.setCodigoActividad(CodigoActividad.trim());
                ModficarActividad.setNombreActividad(NombreActividad.trim());
                ModficarActividad.setEstado(Estado.trim());

                ModificarArchivoTxtActividadDetalle(ListaTA, this.CodigoListaDetalle);
                lblMensaje.setText("Tablero modificado con exito.");
                lblMensaje.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "No puede ingresar un comentario con el campo 'Comentario' vacio. Por favor llenar el campo 'Comentario'");

        }
    }//GEN-LAST:event_btnModificarActividadActionPerformed

    private void btbRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRegresarActionPerformed
        ModificarTareaDetalle tareadetalle = new ModificarTareaDetalle(CodigoListaTarea, CodigoTareaDetalle, NombreTarea, DescTarea, FechaI, FechaF, CodigoTablero, NombreTablero, NombreListadoTarea);
        tareadetalle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btbRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActividadesDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActividadesDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActividadesDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActividadesDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActividadesDetalle("", "", "", "", "", "", "", "", "", "", "", "","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbRegresar;
    private javax.swing.JButton btnModificarActividad;
    private java.awt.Choice ddlEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtnombreActividad;
    // End of variables declaration//GEN-END:variables
}
