/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import metodos.Metodos;

/**
 *
 * @author Eleazar
 */
public class Inicio extends javax.swing.JFrame {

    Metodos metodo = new Metodos();

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        TblListadoTablero.addMouseListener(new MouseAdapter() {
                
            //Funcion al hacer doble clic sobre un registro traer el nombre del tablero
            @Override
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 2) {
                    String CodigoTablero = (String) TblListadoTablero.getValueAt(TblListadoTablero.getSelectedRow(), 0);
                    String NombreTablero = (String) TblListadoTablero.getValueAt(TblListadoTablero.getSelectedRow(), 2);
                    IrListadoTareasTablero(CodigoTablero,NombreTablero);
                    //lblPrueba.setText((String) TblListadoTablero.getValueAt(TblListadoTablero.getSelectedRow(), 0));
                }
            }
        });
        //Mostrar el listado de talberos
        TblListadoTablero.setModel(metodo.ListaTablerosTareas("ListaTableros\\Tableros.txt"));
        TblListadoTablero.getColumnModel().getColumn(0).setMaxWidth(0);
        TblListadoTablero.getColumnModel().getColumn(0).setMinWidth(0);
        TblListadoTablero.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        TblListadoTablero.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

        //tamaño de la columna numerica
        TblListadoTablero.getColumnModel().getColumn(1).setPreferredWidth(1);
        TblListadoTablero.getColumnModel().getColumn(1).setResizable(false);

        this.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        this.setResizable(false); //Que no se pueda cambiar el tamaño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblListadoTablero = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCrearModificarT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tablero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 36))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblListadoTablero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblListadoTablero);
        if (TblListadoTablero.getColumnModel().getColumnCount() > 0) {
            TblListadoTablero.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, 170));

        jLabel1.setText("Listado de Tableros creados:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnCrearModificarT.setText("Crear / Editar Tableros");
        btnCrearModificarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearModificarTActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearModificarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnCrearModificarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearModificarTActionPerformed
        ListadoTablero LTablero = new ListadoTablero();
        LTablero.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        LTablero.setResizable(false); //Que no se pueda cambiar el tamaño
        LTablero.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCrearModificarTActionPerformed

    public void IrListadoTareasTablero(String CodigoTablero,String NombreTablero) {
        ListadoTareas LTareas = new ListadoTareas(CodigoTablero,NombreTablero);
        LTareas.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        LTareas.setResizable(false); //Que no se pueda cambiar el tamaño
        LTareas.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblListadoTablero;
    private javax.swing.JButton btnCrearModificarT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
