/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import AdministrarTablero.Comentarios;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static metodos.ComentariosMetodo.DevolverArrayComentarioArreglo;
import static metodos.ComentariosMetodo.ModificarArchivoTxtComentario;

/**
 *
 * @author Eleazar
 */
public class ModificaComentarios extends javax.swing.JFrame {
    
    String CodigoListaTarea;
    String NombreTarea;
    String DescTarea;
    String FechaI;
    String FechaF;
    String CodigoTablero;
    String NombreTablero;
    String NombreListadoTarea;
    String CodigoTareaDetalle;
    String Comentario;
    String CodigoComentario;

    /**
     * Creates new form ModificaComentarios
     */
    public ModificaComentarios(String CodigoListaTarea, String CodigoTareaDetalle, String NombreTarea, String DescTarea, String FechaI, String FechaF, String CodigoTablero, String NombreTablero, String NombreListaTarea, String Comentario, String CodigoComentario) {
        initComponents();
        if (!"".equals(CodigoListaTarea)) {
            this.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
            this.setResizable(false); //Que no se pueda cambiar el tamaño
            this.CodigoListaTarea = CodigoListaTarea;
            this.CodigoTareaDetalle = CodigoTareaDetalle;
            this.NombreTarea = NombreTarea;
            this.DescTarea = DescTarea;
            this.FechaI = FechaI;
            this.FechaF = FechaF;
            this.CodigoTablero = CodigoTablero;
            this.NombreTablero = NombreTablero;
            this.NombreListadoTarea = NombreListaTarea;
            lblMensajeComentario.setVisible(false);
            this.Comentario = Comentario;
            this.CodigoComentario = CodigoComentario;
            
            txtAreaComentario.setText(Comentario);
        } else {
            Inicio inicio = new Inicio();
            inicio.setVisible(true);
            this.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMensajeComentario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtAreaComentario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Modificar Comentarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMensajeComentario.setText("jLabel1");
        jPanel1.add(lblMensajeComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setText("El comentario se modicará al siguiente mensaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        jPanel1.add(txtAreaComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!"".equals(txtAreaComentario.getText().trim())) {
            String Comentario = txtAreaComentario.getText();
            if (!"".equals(Comentario)) {
                
                ArrayList<Comentarios> comentario = DevolverArrayComentarioArreglo(CodigoTareaDetalle);
                Comentarios listacomentario = comentario.stream().filter(t -> t.getCodigoComentario().equals(this.CodigoComentario)).findFirst().get();
                listacomentario.setCodigoTarea(this.CodigoTareaDetalle);
                listacomentario.setCodigoComentario(this.CodigoComentario);
                listacomentario.setComentario(txtAreaComentario.getText().trim());
                
                ModificarArchivoTxtComentario(comentario, this.CodigoTareaDetalle);
                lblMensajeComentario.setVisible(true);
                lblMensajeComentario.setText("Comentario Modificado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puede ingresar un comentario vacio. Por favor llenar el campo 'Comentario'");
            
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ListaComentarios ventanaListaComentario = new ListaComentarios(this.CodigoListaTarea, this.CodigoTareaDetalle, this.NombreTarea, this.DescTarea, this.FechaI, this.FechaF, this.CodigoTablero, this.NombreTablero, this.NombreListadoTarea);
        ventanaListaComentario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ArrayList<Comentarios> comentario = DevolverArrayComentarioArreglo(CodigoTareaDetalle);
        
        comentario.removeIf(t -> t.getCodigoComentario().equals(this.CodigoComentario));
        
        ModificarArchivoTxtComentario(comentario, this.CodigoTareaDetalle);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txtAreaComentario.setEnabled(false);
        lblMensajeComentario.setVisible(true);
        lblMensajeComentario.setForeground(Color.green);
        lblMensajeComentario.setText("Comentario Eliminado con exito.");
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaComentarios("", "", "", "", "", "", "", "", "", "", "");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensajeComentario;
    private javax.swing.JTextField txtAreaComentario;
    // End of variables declaration//GEN-END:variables
}
