/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import AdministrarTablero.ActividadesLista;
import AdministrarTablero.Tablero;
import AdministrarTablero.Tarea;
import AdministrarTablero.TareaDetalle;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static metodos.ListaActividadesMetodo.DevolverArrayListaActividades;
import metodos.ListadoDeTareas;
import static metodos.ListadoDeTareas.DevolverTablaArregloListadoTarea;
import metodos.Metodos;
import static metodos.Metodos.DevolverTablaArreglo;
import static metodos.Metodos.ModificarArchivoTxt;
import static metodos.Metodos.ModificarArchivoTxtTableros;
import static metodos.MetodosTareaDetalle.DevolverTareaDetalleArreglo;

/**
 *
 * @author Eleazar
 */
public class ModificarTablero extends javax.swing.JFrame {

    private String CodigoTablero;

    /**
     * Creates new form ModificarTablero
     */
    public ModificarTablero(String CodigoT, String NombreT) {
        initComponents();
        this.setLocationRelativeTo(null); //Que cuando aparezca la ventana sea en el centro de la pantalla principal
        this.setResizable(false); //Que no se pueda cambiar el tamaño
        if (!"".equals(CodigoT)) {
            this.CodigoTablero = CodigoT;
            lblNombreTablero.setText("Tablero:" + NombreT);
            txtModificaNombreTablero.setText(NombreT);
            lblErrorTablero.setVisible(false);
        } else {
            ListadoTablero tableros = new ListadoTablero();
            this.setVisible(false);

            tableros.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreTablero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModificaNombreTablero = new javax.swing.JTextField();
        btnGuardarTableroM = new javax.swing.JButton();
        btnEliminarTablero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarListaT = new javax.swing.JButton();
        lblErrorTablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Administrar Tablero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreTablero.setText("Tablero:");
        jPanel1.add(lblNombreTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("Para modificar el nombre del tablero solamente tiene que escribir el ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 380, 20));

        jLabel3.setText("nuevo nombre en el siguiente campo y dar clic en guardar.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        jPanel1.add(txtModificaNombreTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, -1));

        btnGuardarTableroM.setText("Guardar");
        btnGuardarTableroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTableroMActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarTableroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btnEliminarTablero.setText("Eliminar Tablero");
        btnEliminarTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTableroActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel1.setText("Para eliminar el tablero solamente tiene que presionar el boton eliminar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnRegresarListaT.setText("Regresar");
        btnRegresarListaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarListaTActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarListaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        lblErrorTablero.setBackground(new java.awt.Color(255, 0, 0));
        lblErrorTablero.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorTablero.setText("Error");
        jPanel1.add(lblErrorTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarListaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarListaTActionPerformed
        ListadoTablero tableros = new ListadoTablero();
        txtModificaNombreTablero.setText("");
        tableros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarListaTActionPerformed

    private void btnGuardarTableroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTableroMActionPerformed
        String NombreTablero = txtModificaNombreTablero.getText();
        if (!"".equals(NombreTablero)) {
            ArrayList<Tablero> ListaT = DevolverTablaArreglo("ListaTableros\\Tableros.txt");
            Tablero TableroModicar = ListaT.stream().filter(t -> t.getCodigo().equals(this.CodigoTablero)).findFirst().get();
            TableroModicar.setNombre(txtModificaNombreTablero.getText().trim());
            ModificarArchivoTxt(ListaT, "Tableros");
            lblErrorTablero.setText("Tablero modificado con exito.");
            lblErrorTablero.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "El nombre del tablero no puede quedar en blanco");

        }


    }//GEN-LAST:event_btnGuardarTableroMActionPerformed

    private void btnEliminarTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTableroActionPerformed

        Metodos metodo = new Metodos();
        File Archivo;
        ListadoDeTareas listadoTarea = new ListadoDeTareas();
        //eliminamos el listado de tareas que contenga el tablero
        Archivo = new File("C:/Organizador/Tablero/" + this.CodigoTablero + ".txt");
        if (Archivo.isFile()) {
            ArrayList<Tarea> ListadoTarea = listadoTarea.DevolverTablaArregloListadoTarea(this.CodigoTablero);
            System.out.println(Archivo.delete());
            for (Tarea t : ListadoTarea) {
                Archivo = new File("C:/Organizador/ListaTareas/" + t.getCodigo() + ".txt");
                if (Archivo.isFile()) {
                    ArrayList<TareaDetalle> tareaDetalle = DevolverTareaDetalleArreglo(t.getCodigo());
                    System.out.println(Archivo.delete());
                    for (TareaDetalle l : tareaDetalle) {
                        Archivo = new File("C:/Organizador/ListaActividades/" + l.getCodigoTarea() + ".txt");
                        if (Archivo.isFile()) {
                            ArrayList<ActividadesLista> ListaActividad = DevolverArrayListaActividades(l.getCodigoTarea());
                            System.out.println(Archivo.delete());
                            for (ActividadesLista r : ListaActividad) {
                                Archivo = new File("C:/Organizador/Actividades/" + r.getCodigoListaAc() + ".txt");
                                if (Archivo.isFile()) {
                                    System.out.println(Archivo.delete());
                                }
                            }
                        }
                        //busca si hay comentario y los elimina
                        Archivo = new File("C:/Organizador/Comentarios/" + l.getCodigoTarea() + ".txt");
                        if (Archivo.isFile()) {
                            System.out.println(Archivo.delete());
                        }
                    }

                }
            }
        }

        ArrayList<Tablero> ListaTablero = DevolverTablaArreglo("");
        ListaTablero.removeIf(t -> t.getCodigo().equals(this.CodigoTablero));

        ModificarArchivoTxtTableros(ListaTablero);
        btnEliminarTablero.setEnabled(false);
        btnGuardarTableroM.setEnabled(false);
        txtModificaNombreTablero.setEnabled(false);
        lblErrorTablero.setVisible(true);
        lblErrorTablero.setText("Tablero eliminado con exito.");

    }//GEN-LAST:event_btnEliminarTableroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTablero("", "");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarTablero;
    private javax.swing.JButton btnGuardarTableroM;
    private javax.swing.JButton btnRegresarListaT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorTablero;
    private javax.swing.JLabel lblNombreTablero;
    private javax.swing.JTextField txtModificaNombreTablero;
    // End of variables declaration//GEN-END:variables
}
